utils::globalVariables(c(
  "species_code", "survey", "haulcount", "catcount", 
  "meanwgtcpue", "varmnwgtcpue", "meannumcpue", "varmnnumcpue", 
  "biomass", "varbio", "lowerb", "upperb", "population", 
  "varpop", "lowerp", "upperp", "akfin_load_date",
  "afsc_species", "seas", "catch_t", "catch_se", "id",
  "survey_definition_id", "area_type", "design_year",
  "tot", "var", "varg", "stratum_biomass", "regulatory_area_name",
  "abundance_haul", "age", "agency_species_code", "akfin", "area_biomass",
  "area_id", "area_label", "area_name" ,"area_number", "biomass_mt", "biomass_var",
  "blend_tonnage", "bottom_depth", "catch", "cfec_pacfin_species_code",
  "council_management_area", "council_sablefish_management_area",
  "council_sablefish_mgmt_area", "count", "country", "cruisejoin", "distinct",
  "end_latitude", "end_longitude", "exploitable", "fmp_area_code",
  "fmp_management_area", "fmp_subarea", "fmparea", "gear", "gear_temperature",
  "gear_type", "geographic_area_name", "haul_join", "haul_seq", "hauljoin", "join_key",
  "lat_mid", "latitude_dd_end", "latitude_dd_start", "length_mm", "long_mid",
  "longitude_dd_end", "longitude_dd_start", "maturity", "month", "mutate",
  "nontarget_estimate_count", "nontarget_estimate_weight",
  "nontarget_group_name", "performance", "port_join", "pscnq_estimate", "region",
  "select", "sex", "species", "species_group_code", "species_group_name", "species_name",
  "specimenid", "start_date", "stratum", "survey_name", "tons", "tot_g", "total_biomass",
  "trip_target_code", "var_g", "vessel_class", "week_date", "weight", "EXPLOITABLE"
))